@port = 5089
@Server.API_HostAddress = http://localhost:{{port}}

GET {{Server.API_HostAddress}}/api/test
Accept: application/json

###

GET {{Server.API_HostAddress}}/api/whoami
Accept: application/json

###

POST {{Server.API_HostAddress}}/api/login
Content-Type: application/json

{
  "email": "phatvu080903@gmail.com",
  "password": "longPassword@123"
}
